add HA
LibCity/Bigscity-LibCity pull request #164
Opened 2021-09-06 03:10 UTC by XBR-1111

result on METR_LA: 
masked_MAE:  3.6642878
masked_MAPE:  0.08462993326357558
masked_MSE:  40.549553
masked_RMSE:  6.367853

2021-09-13 09:19 UTC, aptx1231 requested changes

2021-09-13 09:19 UTC, aptx1231 commented on test/test_HA.py
> +    path = '../raw_data/' + dataset + '/'
希望是python test/test_HA.py这样运行，这里的路径修改一下

2021-09-13 09:19 UTC, aptx1231 commented on test/test_HA.py
> +    idx_of_timeslots = dict()
idx_of_timeslots 这个用不上吧

2021-09-13 09:19 UTC, aptx1231 commented on test/test_HA.py
> +    data = np.array(data, dtype=float)  # (len(self.geo_ids), len_time, feature_dim)
len(self.geo_ids) --> num_nodes

2021-09-13 09:19 UTC, aptx1231 commented on test/test_HA.py
> +    for i in range(int(t * 0.8), t):
0.8-->test_rate
所以要保留train_rate, eval_rate俩参数，以得到test_rate

2021-09-13 09:19 UTC, aptx1231 commented on test/test_HA.py
> +            y_pred_i += weight[j] * np.mean(data[i - 4 * lag[j]:i:lag[j], :, :], axis=0)
4--> 设成参数

2021-09-13 09:19 UTC, aptx1231 commented on test/test_HA.py
> +    print('masked_MAE: ', masked_mae_np(y_pred, y_true, 0))
补充其他几个metric。全写上。
结果输出到csv或json。

2021-09-14 02:00 UTC, XBR-1111 commented on test/test_HA.py
> +    print('masked_MAE: ', masked_mae_np(y_pred, y_true, 0))
已全部修改

2021-09-14 02:26 UTC, aptx1231 requested changes

2021-09-14 02:26 UTC, aptx1231 commented on test/test_HA.py
> +    data = data.swapaxes(0, 1)  # (len_time, len(self.geo_ids), feature_dim)
num_nodes....

2021-09-14 02:41 UTC, XBR-1111 commented on test/test_HA.py
> +    data = data.swapaxes(0, 1)  # (len_time, len(self.geo_ids), feature_dim)
已修改

2021-09-14 02:47 UTC, aptx1231 approved these changes

2021-09-14 02:49 UTC, merged