SVR add
LibCity/Bigscity-LibCity pull request #166
Opened 2021-09-13 02:30 UTC by buaacjw

2021-09-13 09:20 UTC, aptx1231 requested changes

2021-09-13 09:20 UTC, aptx1231 commented on test/test_svr.py
> +    idx_of_timeslots = dict()
用不上这个，参考一下HA的review，对应也修改一下。

2021-09-13 15:46 UTC, aptx1231 requested changes

2021-09-13 15:46 UTC, aptx1231 commented on test/test_svr.py
> +        'dataset_class': 'TrafficStatePointDataset',
这个没用

2021-09-13 15:46 UTC, aptx1231 commented on test/test_svr.py
> +        'metrics' : ['MAE', 'MAPE', 'MSE', 'RMSE', 'masked_MAE', 'masked_MAPE', 'masked_MSE', 'masked_RMSE', 'R2', 'EVAR']
这个metric没有在evaluate函数用上，应该作为参数传进evaluate吧

2021-09-13 15:46 UTC, aptx1231 commented on test/test_svr.py
> +    config = {
config跟他们一样放在最外边吧

2021-09-13 15:46 UTC, aptx1231 commented on test/test_svr.py
> +    data = dataset._load_dyna_3d("METR_LA")
这几句还是跟他们一样吧，这样调用私有函数不是很好

2021-09-13 15:46 UTC, aptx1231 commented on test/test_svr.py
> +    data = dataset._load_dyna_3d("METR_LA")
而且METR_LA这不硬编码了，config就没用了

2021-09-13 15:46 UTC, aptx1231 commented on test/test_svr.py
> +    # trainX, trainY, testX, testy = preprocess_data(data, config)
没用的注释掉的删掉

2021-09-13 15:46 UTC, aptx1231 commented on test/test_svr.py
> +    metrics =  config.get('matrics', ['MAE', 'MAPE', 'MSE', 'RMSE', 'masked_MAE', 'masked_MAPE', 'masked_MSE', 'masked_RMSE', 'R2', 'EVAR'])
matrics -- 》 metrics

2021-09-13 15:46 UTC, aptx1231 commented on test/test_svr.py
> +        ax = np.reshape(ax, [-1, input_window])  # (train_size, input_window * feature)
这注释不对，这里应该是(train_size * feature, input_window)吧

2021-09-13 15:46 UTC, aptx1231 commented on test/test_svr.py
> +        pre = np.array(np.transpose(np.mat(pre)))
这里还是按照原代码repeat吧

2021-09-13 15:46 UTC, aptx1231 commented on test/test_svr.py
> +    print('=====================')
奇怪的东西删掉

2021-09-13 15:48 UTC, aptx1231 requested changes

2021-09-13 15:48 UTC, aptx1231 commented on test/test_svr.py
> +    df.to_csv("metr_la.csv")
不要硬编码。。可以叫result.csv也行呀。。

2021-09-14 02:34 UTC, aptx1231 requested changes

2021-09-14 02:34 UTC, aptx1231 commented on test/test_svr.py
> +        pre = svr_model.predict(tx)  # (test_size, feature)
从这里开始，后边注释的形状应该是某个地方有问题
pre和ty的注释形状都不一样。。
直到163行，一步一步订正一下

2021-09-14 02:34 UTC, aptx1231 commented on test/test_svr.py
> +
删掉空行，
增加eval_rate

2021-09-14 02:34 UTC, aptx1231 commented on test/test_svr.py
> +    path = '../raw_data/' + dataset + '/'
看HA的代码，希望可以python test/test_svr.py这样运行。
这个函数直接从HA复制吧，包括开头的import部分

2021-09-14 07:59 UTC, buaacjw commented on test/test_svr.py
> +    path = '../raw_data/' + dataset + '/'
已经更改

2021-09-14 07:59 UTC, buaacjw commented on test/test_svr.py
> +
已经删去，增加了eval_rate

2021-09-15 15:13 UTC, aptx1231 requested changes

2021-09-15 15:13 UTC, aptx1231 commented on test/test_svr.py
> +def test(result, testy, config):
不太理解的是，函数名为啥换成test，就不能跟别人写一样的。。

2021-09-15 15:13 UTC, aptx1231 commented on test/test_svr.py
> +    df.to_csv("test_result.csv")
这个名字也是

2021-09-15 15:13 UTC, aptx1231 commented on test/test_svr.py
> +        pre = svr_model.predict(tx)  # (test_size, )
我觉得这里的形状是（test_size * feature, ），这样ty和pre才对得上。
后边也是。

2021-09-15 15:50 UTC, aptx1231 requested changes

2021-09-15 15:50 UTC, aptx1231 commented on test/test_svr.py
> +def preprocess_data(data, config):
请把这个函数 统一换成

`def preprocess_data(data):
    train_rate = config.get('train_rate', 0.7)
    eval_rate = config.get('eval_rate', 0.1)

    input_window = config.get('input_window', 12)
    output_window = config.get('output_window', 3)

    x, y = [], []
    for i in range(len(data) - input_window - output_window):
        a = data[i: i + input_window + output_window]
        x.append(a[0: input_window])
        y.append(a[input_window: input_window + output_window])
    x = np.array(x)
    y = np.array(y)

    train_size = int(x.shape[0] * (train_rate + eval_rate))
    trainX = x[:train_size]
    trainY = y[:train_size]
    testX = x[train_size:x.shape[0]]
    testY = y[train_size:x.shape[0]]
    return trainX, trainY, testX, testY
`

2021-09-15 15:51 UTC, buaacjw commented on test/test_svr.py
> +def test(result, testy, config):
因为想和eval区分开...

2021-09-15 16:01 UTC, aptx1231 commented on test/test_svr.py
> +def test(result, testy, config):
跟其他几位统一吧

2021-09-18 07:38 UTC, aptx1231 approved these changes

2021-09-20 02:10 UTC, merged