add ARIMA
LibCity/Bigscity-LibCity pull request #169
Opened 2021-09-15 08:27 UTC by l782993610

2021-09-15 15:57 UTC, aptx1231 requested changes

2021-09-15 15:57 UTC, aptx1231 commented on test/test_ARIMA.py
> +    for p in range(0, 4):
p d q的范围上届可以换成参数吗

2021-09-15 15:57 UTC, aptx1231 commented on test/test_ARIMA.py
> +    evaluate(y_pred, y_true)
本质上来说是没啥问题的，但是为了满足我们多不预测的要求，只能在输出之后做一点处理了。
我的想法是：1是要利用上train_rate和eval_rate，2是要切分input_window和output_window。
我觉得可以用preprocess_data函数对数据进行切片，跟R那个模型是比较像的，你应该了解这个。
y_pred, y_true都切，得到测试集上的预测目标和预测真值，对应到preprocess_data函数就是testY。
在两个testY上evaluate。
你的evaluate也要改下，用VAR现成的就行，以进行多步预测。

2021-09-15 15:57 UTC, aptx1231 commented on test/test_ARIMA.py
> +    evaluate(y_pred, y_true)
preprocess_data函数在群里。

2021-09-17 09:36 UTC, l782993610 commented on test/test_ARIMA.py
> +    evaluate(y_pred, y_true)
改了一下，现在是把按照 process data 函数划分的数据集。这样划分出来 X 是 (总时间步步数，输入窗口，传感器，特征数），对每一个时间步，每一个节点分别使用 ARIMA 预测，该预测基于 12 步的输入窗口数据输出 3 步输出窗口数据。

2021-09-17 09:36 UTC, l782993610 commented on test/test_ARIMA.py
> +    for p in range(0, 4):
改成了 p, d, q range

2021-09-17 15:15 UTC, aptx1231 approved these changes

2021-09-19 11:15 UTC, merged