CSTN
LibCity/Bigscity-LibCity pull request #197
Opened 2021-10-31 03:32 UTC by l782993610

2021-10-31 12:55 UTC, aptx1231 requested changes
1.解决冲突
2.跑的结果发我一下

2021-10-31 12:55 UTC, aptx1231 commented on libcity/data/dataset/acfm_dataset.py
> +
删掉，不要改不需要改的文件

2021-10-31 12:55 UTC, aptx1231 commented on libcity/data/dataset/cstn_dataset.py
> +                加载数据文件(.gridod)和外部数据(.ext)，以X, W, y的形式返回
前边空格有点多

2021-10-31 13:27 UTC, aptx1231 commented
对了，这个有开源数据，所以要比一比性能

2021-11-07 07:24 UTC, l782993610 commented
🤔，在 review 通过之前没法解决 merge 冲突。俺先去跑一下这个

2021-11-07 07:44 UTC, aptx1231 submitted a review, later dismissed

2021-11-08 12:23 UTC, aptx1231 requested changes

2021-11-08 12:23 UTC, aptx1231 commented on libcity/config/task_config.json
> -    "eta": {
为什么把这个删掉？

2021-11-08 12:23 UTC, aptx1231 commented on libcity/config/task_config.json
> -        "GSNet": {
这里也是

2021-11-08 12:23 UTC, aptx1231 commented on libcity/model/traffic_flow_prediction/STSGCN.py
> +from logging import getLogger
为什么修改这个文件？

2021-11-08 12:23 UTC, aptx1231 commented on libcity/model/traffic_od_prediction/__init__.py
> +from libcity.model.traffic_od_prediction.CSTN import CSTN
为什么import两次

2021-11-08 12:46 UTC, closed without merging