'node2vec'
LibCity/Bigscity-LibCity pull request #206
Opened 2021-11-11 09:25 UTC by nadiaaaaachen

2021-11-12 03:04 UTC, WenMellors requested changes
大致看了下代码，比上次 commit 的要好很多了，只是看上去还没有写完。结合着目前给的建议再修改一下吧。有什么问题直接在 review 的评论下回复就可以了。

2021-11-12 03:04 UTC, WenMellors commented on test/test_node2vec.py
> +    NV.sentence_form_rel()
sentence_form_rel 似乎是在干缓存游走轨迹的事？
如果是要缓存的话，建议直接存成 JSON。因为感觉存成 rel 格式，你要读取缓存的时候，将 rel 还原为游走轨迹应该还挺麻烦的。

2021-11-12 03:04 UTC, WenMellors commented on test/test_node2vec.py
> +    NV._load_rel()
这里是想读取缓存？
感觉游走完轨迹之后，应该是基于游走得到的轨迹基于 word2vec 来计算每个点的 embedding 向量了？

2021-11-17 09:37 UTC, WenMellors commented
改动：
1、把aliamethod放到了libcity/utils文件夹下
2、去掉了node2vec_dataset中特征处理和邻接矩阵转换的部分 直接把游走结果的二维list分为训练验证测试三个部分
3、node2vec模型部分去掉了并行计算
4、node2vec_test部分添加了wordvec模型
> copy from https://github.com/LibCity/Bigscity-LibCity/pull/208

2021-11-17 10:11 UTC, WenMellors requested changes

2021-11-17 10:11 UTC, WenMellors commented on test/test_node2vec.py
> +    data.train_dataloader, data.eval_dataloader, data.test_dataloader = data.get_data()
感觉框架流程或者说路网表征的任务理解上还是有点问题。Dataset 是读取原子文件，准备好数据给模型用。对于 Node2Vec 而言，个人认为 ReadGraph 目前实现的读取图的工作才应该是 Dataset 干的。而 Node2vecDataset 目前功能有点看不懂，感觉不需要把游走得到的 list 划分一个训练、验证、测试集吧？看你 learn_embedding 也没有用到。

2021-11-17 10:11 UTC, WenMellors commented on test/test_node2vec.py
> +    data.train_dataloader, data.eval_dataloader, data.test_dataloader = data.get_data()
所以个人感觉你把 ReadGraph 做成 Node2vecDataset 负责生成图，然后传给 Node2vec 模型。然后感觉 learning_embeddings 也放到 Node2vec 里面比较好，因为 Node2vec 不仅仅是游走，还有游走之后计算表征，所以感觉这个函数应该放到 Node2vec 里面。

2021-11-17 10:11 UTC, WenMellors commented on test/test_node2vec.py
> +    data.train_dataloader, data.eval_dataloader, data.test_dataloader = data.get_data()
最后你的这个 test_node2vec.py 再整理下就可以做成 executor 了，来跑 Node2vec

2021-11-19 12:30 UTC, WenMellors reviewed
似乎没有什么大问题

2021-11-19 12:30 UTC, WenMellors commented on libcity/model/road_representation/node2vec.py
> +        save_path = 'libcity/cache/{}_embedding.bin'.format(self.dataset)
这里存储可以把特征矩阵做成 np.array，然后用 np.save 保存成 .npy 后缀的文件吗？这样读取会方便点。

2021-11-30 03:01 UTC, WenMellors requested changes
还需要修改一下，才能够通过 `python run_model.py` 运行你的代码

2021-11-30 03:02 UTC, WenMellors commented
> 还需要修改一下，才能够通过 `python run_model.py` 运行你的代码

也就是说，你需要保证能够通过 python run_model.py 能够运行 Node2Vec 模型并输出随机游走后的特征矩阵

2021-11-30 03:02 UTC, WenMellors commented
麻烦再改一下吧

2021-11-30 06:59 UTC, WenMellors reviewed
你现在能从 run_model.py 脚本开始跑吗？

2021-11-30 06:59 UTC, WenMellors commented on libcity/config/task_config.json
> +            "evaluator" : "Node2VecEvaluator"
似乎并没有这个类吧？你可以写上 `RoadRepresentationEvaluator`

2021-11-30 06:59 UTC, WenMellors commented on libcity/config/evaluator/Node2VecEvaluator.json
> +{
没有看到对应的评估类呢？

2021-11-30 07:17 UTC, nadiaaaaachen commented on libcity/config/task_config.json
> +            "evaluator" : "Node2VecEvaluator"
pipeline文件里面有有个ray库 from ray import tune 我好像查不到这个库

2021-11-30 07:30 UTC, WenMellors commented on libcity/config/task_config.json
> +            "evaluator" : "Node2VecEvaluator"
这个的依赖都写到了 requirements.txt 里面。你执行了这个命令了吗？安装 python 依赖包
```
pip install -r requirements.txt
```

2021-11-30 07:36 UTC, WenMellors reviewed
能用 run_model.py 跑之后，就可以合并进去了

2021-11-30 07:52 UTC, nadiaaaaachen commented
我把ray那个框架去掉以后可以用 run_model.py 跑

2021-11-30 08:11 UTC, WenMellors commented
好的吧，但还是可以把环境配好。就只需要执行一下一个命令就行。

>这个的依赖都写到了 requirements.txt 里面。你执行了这个命令了吗？安装 python 依赖包
>```
>pip install -r requirements.txt
>```

2021-11-30 08:12 UTC, WenMellors approved these changes

2021-11-30 08:14 UTC, WenMellors commented
还有个 git 冲突需要解决。git 冲突是因为你修改的文件，别人也修改过然后他比你先合进了 master 分支。这个在日常开发中还挺常见的。可以试着解决一下。Github 应该是支持直接在网页端解决冲突，就点那个 Resolve Conflicts，然后把冲突的地方改一下就行

2021-11-30 08:43 UTC, WenMellors approved these changes
ok

2021-12-01 03:27 UTC, merged