GeomGCN cpu
LibCity/Bigscity-LibCity pull request #207
Opened 2021-11-16 01:08 UTC by Aressfull

2021-11-16 03:49 UTC, aptx1231 commented
要在GPU上测试通过

2021-11-17 03:14 UTC, WenMellors requested changes
最好能够给 GeomGCN 再增加点注释，比如不是抽象类定义的那些方法（get_input）的输入输出是什么。
注释格式可以参考下面：
```
def forward(self, query, key, mask=None):
        """前馈
        Args:
            query (tensor): shape (batch_size, hidden_size)
            key (tensor): shape (batch_size, seq_len, hidden_size)
            mask (tensor): padding mask, 1 表示非补齐值, 0 表示补齐值 shape (batch_size, seq_len)
        Return:
            attn_hidden (tensor): shape (batch_size, hidden_size)
        """
```
这个就是 docstring，你用 vscode 或者 pycharm 应该都是有插件能辅助生成的。

2021-11-17 03:14 UTC, WenMellors commented on libcity/model/road_representation/GeomGCN.py
> +        np.save('./libcity/cache/evaluate_cache/embedding_{}_{}_{}.npy'
这里是在做什么？保存生成的 N*F 特征矩阵？

2021-11-20 09:50 UTC, Aressfull commented on libcity/model/road_representation/GeomGCN.py
> +        np.save('./libcity/cache/evaluate_cache/embedding_{}_{}_{}.npy'
从ChebConv.py里移过来的，应该是在保存encode结束后的输出结果，因为用的自回归，所以把这个中间状态保存一下

2021-11-20 10:07 UTC, aptx1231 commented on libcity/model/road_representation/GeomGCN.py
> +        np.save('./libcity/cache/evaluate_cache/embedding_{}_{}_{}.npy'
保留表征结果

2021-11-21 16:30 UTC, aptx1231 requested changes

2021-11-21 16:30 UTC, aptx1231 commented on libcity/model/road_representation/GeomGCN.py
> +        # adj_mx = adj_mx.A
删掉没用的注释行

2021-12-16 02:32 UTC, Aressfull commented on libcity/model/road_representation/GeomGCN.py
> +        # adj_mx = adj_mx.A
已删除

2021-12-16 02:34 UTC, Aressfull commented
> 要在GPU上测试通过

已通过，但GPU上运行速度依然很慢，而且准确率从头到尾没有变过，不太清楚原因

2021-12-16 02:41 UTC, aptx1231 commented
不应该使用.cuda()。而是.to(device)。
device从config中取得

2021-12-16 02:47 UTC, WenMellors requested changes

2021-12-16 02:47 UTC, WenMellors commented on libcity/model/road_representation/GeomGCN.py
> +                Args:
这个缩进不对呢，都多了一个 tab 的样子

2021-12-16 02:47 UTC, WenMellors commented on libcity/model/road_representation/GeomGCN.py
> +        g = g.to(torch.device('cuda:0'))
这里强制指定为 cuda:0 ? 要么直接 `.cuda()` 要么 `.to(config['device'])`

2021-12-16 02:47 UTC, WenMellors commented on libcity/model/road_representation/GeomGCN.py
> +        g = g.to(torch.device('cuda:0'))
记得你应该再 gpu_id 3 上跑过？这样写不会报错是吗？

2021-12-16 03:12 UTC, WenMellors commented
> 不应该使用.cuda()。而是.to(device)。 device从config中取得

今天刚发现，在 ConfigParser 里面设置了 `torch.cuda.set_device(gpu_id)`。 所以你之前用 .cuda() 应该是可以跑起来的，但为了统一还是 to(device) 比较好。

再加上 torch 官方文档里关于 set_device 函数有个 comment:
> Usage of this function is discouraged in favor of device. In most cases it’s better to use CUDA_VISIBLE_DEVICES environmental variable.

或许我们后续会改掉这一函数的使用，所以你还是全部改成 `to(device)` 会好一点。

2021-12-16 06:20 UTC, Aressfull commented on libcity/model/road_representation/GeomGCN.py
> +                Args:
已修改

2021-12-16 06:21 UTC, Aressfull commented on libcity/model/road_representation/GeomGCN.py
> +        g = g.to(torch.device('cuda:0'))
好的，已经改过来了，但好像还是没有对训练过程产生影响

2021-12-16 07:56 UTC, aptx1231 commented
差不多可以，但是需要解决冲突才能合并

2021-12-16 10:43 UTC, WenMellors submitted a review, later dismissed

2021-12-27 11:45 UTC, Aressfull commented
已解决冲突

2022-01-04 15:25 UTC, merged