GAT
LibCity/Bigscity-LibCity pull request #213
Opened 2021-11-21 16:24 UTC by Qwtdgh

GAT机制实现路网表征——曲乐皓
助教您好，
目前代码已在服务器跑通，已基本解决问题，新添加GAT模块
已完成的任务有
1.生成log文件，但是loss的值在0.0136左右，无法下降。
2.用.csv文件生成了聚类图象，并于ChechConv进行了对比。

2021-11-21 16:28 UTC, aptx1231 requested changes

2021-11-21 16:28 UTC, aptx1231 commented on libcity/model/road_representation/GAT.py
> +        print("---------------")
删掉

2021-11-21 16:28 UTC, aptx1231 commented on libcity/model/road_representation/GAT.py
> +        print("---------------")
无用的print

2021-11-21 16:28 UTC, aptx1231 commented on libcity/model/road_representation/GAT.py
> +        # self.encoder1 = GATLayer(num_in_features=self.feature_dim, num_out_features=self.output_dim,
删掉

2021-11-21 16:28 UTC, aptx1231 commented on libcity/model/road_representation/GAT.py
> +        # print("***********")
删掉

2021-11-21 16:28 UTC, aptx1231 commented on libcity/config/model/road_representation/GAT.json
> +  "max_diffusion_step": 2,
这俩参数没用上吧，删掉。后边模型从config取的代码也删掉

2021-11-21 16:30 UTC, Qwtdgh commented on libcity/model/road_representation/GAT.py
> +        print("---------------")
收到

2021-11-21 16:30 UTC, Qwtdgh commented on libcity/model/road_representation/GAT.py
> +        print("---------------")
立马就修改

2021-11-21 16:36 UTC, aptx1231 commented on libcity/config/model/road_representation/GAT.json
> +  "max_diffusion_step": 2,
here

2021-11-21 16:42 UTC, Qwtdgh commented on libcity/config/model/road_representation/GAT.json
> +  "max_diffusion_step": 2,
好嘞，助教已经修改完啦

2021-11-23 02:42 UTC, WenMellors requested changes
几个小问题

2021-11-23 02:42 UTC, WenMellors commented on libcity/model/road_representation/GAT.py
> +        GATLayer = GATLayerImp3
为什么要这么做呢？直接这么写会有问题吗？
```
self.encoder = GATLayerImp3(num_in_features=self.feature_dim, num_out_features=self.output_dim,
                                num_of_heads=10, concat=False)
```

2021-11-23 02:42 UTC, WenMellors commented on libcity/model/road_representation/GAT.py
> +def get_layer_type(layer_type):
这个方法似乎并没有使用上？

2021-11-23 02:42 UTC, WenMellors commented on libcity/model/road_representation/GAT.py
> +    IMP1 = 0,
可以适当增加注释，比如这里解释下三个类型分别对应的意义是什么？格式可以参考 google docstring 的风格，如下例：
```
def forward(self, query, key, mask=None):
        """前馈
        Args:
            query (tensor): shape (batch_size, hidden_size)
            key (tensor): shape (batch_size, seq_len, hidden_size)
            mask (tensor): padding mask, 1 表示非补齐值, 0 表示补齐值 shape (batch_size, seq_len)
        Return:
            attn_hidden (tensor): shape (batch_size, hidden_size)
        """
```
这个 vscode 上是有插件能辅助生成 docstring 的，其他 IDE 应该也有。

2021-11-23 02:42 UTC, WenMellors commented on libcity/model/road_representation/GAT.py
> +        GATLayer = GATLayerImp3
看上去是因为目前并没有实现用参数控制是使用 IMP1 还是 IMP2 还是 IMP3？而是默认使用 IMP3?

2021-11-23 02:42 UTC, WenMellors commented on libcity/model/road_representation/GAT.py
> +        scores_source = scores_source.index_select(self.nodes_dim, src_nodes_index.to(device="cuda"))
建议所有 `.to(device=)` 的函数都写成 `.to(device=self.device)` 就是统一用 config 传来的 device 参数。这样尽可能保证不会出现计算输入的张量不在同一个设备上，导致的报错。
目前这样的写法在 cpu 上跑的时候不会出错吗？

2021-11-23 02:42 UTC, WenMellors commented on libcity/model/road_representation/GAT.py
> +        scores_source = scores_source.index_select(self.nodes_dim, src_nodes_index.to(device="cuda"))
因为我们提供的脚本 run_model.py 中有两个参数是 --gpu 与 --gpu_id，用以让用户能够自由切换所要使用的计算设备（CPU/GPU/在有多张 GPU 时指定某一 GPU）。所以 config 中都会带一个 device 参数，来表明本次实验是在哪一个设备上运行的。

2021-11-23 02:42 UTC, WenMellors commented on libcity/model/road_representation/GAT.py
> +        GATLayer = GATLayerImp3
仅为个人理解，如果只允许用 IMP3，那就把这里写的更简洁一点吧

2021-11-23 02:44 UTC, WenMellors commented
解决了的问题，可以点 Resolve Conversation。标记这个问题已经被解决了。这样就可以很清楚的看到还剩什么问题没有解决了。

2021-11-23 03:01 UTC, aptx1231 commented on libcity/model/road_representation/GAT.py
> +        scores_source = scores_source.index_select(self.nodes_dim, src_nodes_index.to(device="cuda"))
device这里要改一下，其他地方应该是之前的仓库实现了多样的gat，然后他用的最高级的GATLayerImp3，就都留着吧，之后我们说不定也会用到别的。

2021-11-23 05:55 UTC, Qwtdgh commented on libcity/model/road_representation/GAT.py
> +    IMP1 = 0,
好的，助教，我增加一下注释，此方法主要是选择IMP的类型，目前是使用了最高级的IMP3，所以可能没有用上，建议还是保留一下

2021-11-23 06:01 UTC, Qwtdgh commented on libcity/model/road_representation/GAT.py
> +        scores_source = scores_source.index_select(self.nodes_dim, src_nodes_index.to(device="cuda"))
这个device是为了在咱们的服务器上运行才添加的，在之前的原码中是没有.to(device="cuda")的。
要是`.to(device="cpu")`就无法在服务器上运行，并且我看ChebConv中 self.device的定义就是"cpu"，所以用`.to(device=self.device)`，还是不太会改的

目前这样的写法在 cpu 上跑应该会报错的。

2021-11-23 06:15 UTC, Qwtdgh commented on libcity/model/road_representation/GAT.py
> +        GATLayer = GATLayerImp3
现在使用的是最高级的IMP3，也可以使用其他的IMP，您看保留其他的IMP可以嘛

2021-11-23 06:18 UTC, Qwtdgh commented on libcity/model/road_representation/GAT.py
> +def get_layer_type(layer_type):
修改后，我使用了一下，`GATLayer = GATLayerImp3`  改成了`GATLayer = get_layer_type(2)`
主要是此方法可以兼容其他的IMP，建议保留

2021-11-23 06:19 UTC, aptx1231 commented on libcity/model/road_representation/GAT.py
> +        scores_source = scores_source.index_select(self.nodes_dim, src_nodes_index.to(device="cuda"))
self.device是从config里取出来的
所有用到device的地方，都换成从config取出来的config['device']
ChebNet里边的self.device = config.get('device', torch.device('cpu'))，就是从config取，没取到的话为cpu。

2021-11-23 06:20 UTC, aptx1231 commented on libcity/model/road_representation/GAT.py
> +        scores_source = scores_source.index_select(self.nodes_dim, src_nodes_index.to(device="cuda"))
就是你的device不能device='cuda'，而是从config取出来的一个参数，而不是固定的'cuda'

2021-11-23 06:21 UTC, WenMellors commented on libcity/model/road_representation/GAT.py
> +    IMP1 = 0,
明白了

2021-11-23 06:22 UTC, Qwtdgh commented on libcity/model/road_representation/GAT.py
> +        scores_source = scores_source.index_select(self.nodes_dim, src_nodes_index.to(device="cuda"))
关于这个`device`的修改，我确实不太会，可能要花些时间修改

2021-11-23 06:25 UTC, WenMellors commented on libcity/model/road_representation/GAT.py
> +        scores_source = scores_source.index_select(self.nodes_dim, src_nodes_index.to(device="cuda"))
就是在你 GAT 的 `__init__` 函数里加一句：
```
self.device = config.get('device', torch.device('cpu'))
```
然后把后面的所有 `.to(device='cuda')` 的地方改成 `.to(device=self.device)` 的就可以了。如果你想知道 config 里 device 是怎么定义的可以参见 `/config/config_parser.py ` 的 `_init_device` 方法。如下：

```
def _init_device(self):
        use_gpu = self.config.get('gpu', True)
        gpu_id = self.config.get('gpu_id', 0)
        if use_gpu:
            torch.cuda.set_device(gpu_id)
        self.config['device'] = torch.device(
            "cuda:%d" % gpu_id if torch.cuda.is_available() and use_gpu else "cpu")
```

2021-11-23 06:32 UTC, aptx1231 commented on libcity/model/road_representation/GAT.py
> +        scores_source = scores_source.index_select(self.nodes_dim, src_nodes_index.to(device="cuda"))
你的device是从外边传进Model里边的config中取出来的，不是硬编码的，这有啥不明白的？

2021-11-23 10:07 UTC, Qwtdgh commented on libcity/model/road_representation/GAT.py
> +        scores_source = scores_source.index_select(self.nodes_dim, src_nodes_index.to(device="cuda"))
ok，已解决，可以在服务器上运行了

2021-11-23 10:07 UTC, Qwtdgh commented on libcity/model/road_representation/GAT.py
> +        scores_source = scores_source.index_select(self.nodes_dim, src_nodes_index.to(device="cuda"))
已经push了

2021-11-24 02:53 UTC, WenMellors reviewed
已经在服务器上跑过了吧？

2021-11-24 14:50 UTC, Qwtdgh commented
> 已经在服务器上跑过了吧？

是的，已经跑过了

2021-11-25 02:28 UTC, WenMellors approved these changes
我没有问题了

2021-11-26 01:51 UTC, aptx1231 approved these changes

2021-11-26 01:54 UTC, merged