[Work In Process] Modularize Layer
LibCity/Bigscity-LibCity pull request #230
Opened 2021-12-09 07:05 UTC by WenMellors

2021-12-09 07:22 UTC, WenMellors reviewed
先对 Embedding 提了点想法

2021-12-09 07:22 UTC, WenMellors commented on libcity/layer/Spatial/embedding.py
> +class Embed(nn.Module):
仅对 Embed 和 MultiEmbed，感觉做更细粒度一点，可以抽象两个东西：
* 基础的 nn.Embedding，通过配置字典大小、嵌入向量维度这些。
* 一个是对连续变量基于线性插值实现的 Embedding 层（也就是 delta 那部分）。有这个模块是因为 Embedding 只能对离散整数做嵌入，所以对于连续变量需要使用这种线性插值的方式解决 Embedding 嵌入（如距离）。

然后对于 Joint 把 Embedding 的向量拼起来，感觉可以拿到外面，然后用一个 concat 算子来解决。这样可能通用性要高一点？当然也可以保留一个 Joint-Embedding 这类似的模块，来减轻工作量。

2021-12-13 06:19 UTC, aptx1231 requested changes
一步一步走：
- 基础的CNN/GNN/RNN/TCN模型实现
- RNN+GNN的融合框架
- RNN+CNN的融合框架
- CNN/TCN+GNN的融合框架
- 可以把GMAN和transformer的代码全删了

2021-12-13 06:19 UTC, aptx1231 commented on .gitignore
> +*.ipynb
没必要修改gitignore

2021-12-13 06:19 UTC, aptx1231 commented on libcity/layer/Output/encoder_decoder.py
> +import torch
这个文件没啥用

2021-12-13 06:19 UTC, aptx1231 commented on libcity/layer/Output/mlp.py
> +class FC(nn.Module):  # is_training: self.training
全连接这么复杂吗

2021-12-13 06:19 UTC, aptx1231 commented on libcity/layer/Output/atten.py
> +        self.input_query_fc = FC(input_dims=self.D, units=self.D, activations=nn.ReLU,
transformer的全连接没有这么复杂吧

2021-12-13 06:19 UTC, aptx1231 commented on libcity/layer/readme.md
> +|Spatial.embedding.PositionalEmbedding|DCRNN| × |
DCRNN里边没有PE

2021-12-13 06:19 UTC, aptx1231 commented on libcity/layer/Temporal/tcn.py
> +
增加Wave Net

2021-12-13 06:19 UTC, aptx1231 commented on libcity/layer/Temporal/cnn.py
> +class TemporalCONV(nn.Module):
时间的CNN应该是一维的？
这个好像是ASTGCN的，建议想办法精简，本质上应该是CONV1D，但是由于我们的数据是2D，它采用的2D。
但是模块化的角度不应该是2D CNN。

2021-12-13 06:19 UTC, aptx1231 commented on libcity/layer/Temporal/cnn.py
> +class CONVGCN(nn.Module):
FUSION

2021-12-13 06:19 UTC, aptx1231 commented on libcity/layer/Temporal/rnn.py
> +        state = state.to(x.device)
这个是GRU

2021-12-13 06:19 UTC, aptx1231 commented on libcity/layer/Temporal/rnn.py
> +        if self.device:
这个是融合

2021-12-13 06:19 UTC, aptx1231 commented on libcity/layer/readme.md
> +|Temporal.atten.TemporalAttention|GMAN|  √  |
GMAN相关的都可以删掉

2021-12-13 06:24 UTC, aptx1231 commented
经典模型（空+时）：
ST-ResNet=CNN+RNN
DCRNN=GCN+RNN
STGCN=GCN+CNN
GWNET=GCN+TCN/Wavenet
ASTGCN=Atten+GCN+CNN，不同模型的Atten实现差距极大，如何分解需要之后解决
AGCRN=GCN+RNN
MTGNN=GCN+TCN/Wavenet
...
可以按照类别实现，比如实现了GCN+RNN的模型，那就可以尝试是不是可以用它来表达出DCRNN+AGCRN

2021-12-17 11:55 UTC, aptx1231 requested changes

2021-12-17 11:55 UTC, aptx1231 commented on libcity/layer/utils.py
> +
这里边好多都是做同一个事的代码，只是不同的人的写法不同

2021-12-17 11:55 UTC, aptx1231 commented on libcity/layer/Spatial/gnn.py
> +            supports.append(calculate_scaled_laplacian(adj_mx, lambda_max=None))
这个模块包含了K阶切比雪夫卷积、K阶扩散卷积

2021-12-17 11:55 UTC, aptx1231 commented on libcity/layer/Spatial/gnn.py
> +            if self.dataset_class == "TGCLSTMDataset":
额

2021-12-17 11:56 UTC, aptx1231 commented on libcity/layer/utils.py
> +
还有就是有一些稀疏矩阵、有一些是普通矩阵

2022-01-06 02:12 UTC, aptx1231 requested changes

2022-01-06 02:12 UTC, aptx1231 commented on libcity/layer/Temporal/tcn.py
> +        self.tconv = nn.ModuleList()
少点啥

2022-02-18 12:22 UTC, ShotDownDiane commented on libcity/layer/Spatial/embedding.py
> +class Embed(nn.Module):
啊呀，我之前都没看到，不好意思

2023-12-04 03:48 UTC, closed without merging