Add model DSTAGNN
LibCity/Bigscity-LibCity pull request #406
Opened 2024-04-09 07:06 UTC by hczs

## 任务执行配置信息
数据集文件配置（DSTAGNNDataset.json），跑 PEMSD4 数据集时要调整 batch_size 参数为 32
```json
{
  "batch_size": 64,
  "cache_dataset": true,
  "num_workers": 0,
  "train_rate": 0.6,
  "eval_rate": 0.2,
  "scaler": "standard",
  "load_external": false,
  "normal_external": false,
  "ext_scaler": "none",
  "input_window": 12,
  "output_window": 12,
  "sparsity": 0.01,
  "period": 288
}
```
模型参数配置（DSTAGNN.json）
```json
{
  "max_epoch": 100,

  "learner": "adam",
  "learning_rate": 0.0001,
  "use_early_stop": false,

  "in_channels": 1,
  "nb_block": 4,
  "K": 3,
  "nb_chev_filter": 32,
  "nb_time_filter": 32,
  "d_model": 512,
  "d_k": 32,
  "n_heads": 3,
  "graph_use": "AG"
}
```
## 任务执行结果
模型评价指标对比如下
- PEMSD4
  | PEMSD4 | LibCity | DSTAGNN |
  | ---- | ---- | ---- |
  |  MAE |  19.63 | 19,28 |
  | RMSE |  31.89 |  31.37 |
  | MAPE |  13.15% |  12.72% |

- PEMSD8
  | PEMSD8 | LibCity | DSTAGNN |
  | ---- | ---- | ---- |
  |  MAE |  16.11 | 15.81 |
  | RMSE |  25.15 |  25.03 |
  | MAPE |  10.44% |  9.92% |

2024-04-14 11:52 UTC, Kazeya27 requested changes

2024-04-14 11:52 UTC, Kazeya27 commented on libcity/model/loss.py
> +    loss_func = torch.nn.SmoothL1Loss()
smooth_l1_loss需要按官方公式重新实现，类似huber_loss

2024-04-15 02:02 UTC, hczs commented on libcity/model/loss.py
> +    loss_func = torch.nn.SmoothL1Loss()
已经按照官方公式重新实现：https://github.com/LibCity/Bigscity-LibCity/pull/406/commits/b66bbff3f01893b4fab4810cd5ea0f0d306f0b05

2024-04-15 10:37 UTC, Kazeya27 approved these changes

2024-04-15 10:37 UTC, merged