Add model TESTAM
LibCity/Bigscity-LibCity pull request #413
Opened 2024-05-10 06:42 UTC by hczs

## 任务执行配置信息
数据集配置文件（TrafficStatePointDataset.json）
```json
{
  "batch_size": 16,
  "cache_dataset": true,
  "num_workers": 0,
  "pad_with_last_sample": false,

  "train_rate": 0.7,
  "eval_rate": 0.1,

  "scaler": "standard",
  "load_external": true,
  "normal_external": false,
  "ext_scaler": "none",
  "input_window": 12,
  "output_window": 12,
  "add_time_in_day": true,
  "add_day_in_week": false
}

```
模型配置文件（TESTAM.json）
```json
{
  "max_epoch": 100,

  "learner": "adam",
  "learning_rate": 1e-3,
  "lr_beta1": 0.9,
  "lr_beta2": 0.98,
  "lr_epsilon": 1e-9,

  "lr_decay": true,
  "lr_scheduler": "cosinewarmupscheduler",
  "n_warmup_steps": 4000,
  "lr_mul": 1,

  "use_early_stop": true,
  "patience": 15,

  "clip_grad_norm": true,
  "max_grad_norm": 5,

  "dropout": 0.0,
  "prob_mul": false,
  "input_dim": 2,
  "hidden_size": 32,
  "layers": 3,
  "is_quantile": true,
  "quantile": 0.7
}
```

## 任务执行结果
模型评价指标对比如下
- METR_LA
  | METR_LA | LibCity | TESTAM |
  | ---- | ---- | ---- |
  |  MAE |  3.46 | 3.36 |
  | RMSE |  7.31 |  7.09 |
  | MAPE |  10.06% |  9.67% |

- PEMS_BAY
  | PEMS_BAY | LibCity | TESTAM |
  | ---- | ---- | ---- |
  |  MAE |  1.89 | 1.85 |
  | RMSE |  4.41 |  4.33 |
  | MAPE |  4.40% |  4.31% |

2024-05-10 07:31 UTC, Kazeya27 requested changes

2024-05-10 07:31 UTC, Kazeya27 commented on libcity/model/traffic_speed_prediction/TESTAM.py
> +        if self.training:
这个self.training模型里面没有定义过，在config文件没有指定loss函数时，Executor会用calculate_loss函数作为训练的损失函数。我看你这里本意应该是训练的时候用前一个分支，评估的时候用后一个分支，在executor类里面改改吧。

2024-05-11 06:10 UTC, hczs commented on libcity/model/traffic_speed_prediction/TESTAM.py
> +        if self.training:
代码已修改，已将训练时用的损失函数添加至executor中，具体修改请查看：https://github.com/LibCity/Bigscity-LibCity/pull/413/commits/87feed784e3ef6a5461e77084298831dbba3434a

2024-05-12 09:37 UTC, Kazeya27 approved these changes

2024-05-13 06:45 UTC, merged