use time_intervals to calculate points_per_hour
LibCity/Bigscity-LibCity pull request #425
Opened 2024-06-17 06:32 UTC by hczs

2024-06-21 16:04 UTC, Kazeya27 requested changes

2024-06-21 16:04 UTC, Kazeya27 commented on libcity/config/data/STPGCNDataset.json
> +  "time_intervals": 720,
你理解错我的意思了，time_intervals这个属性在dataset类里会返回的

2024-06-25 01:35 UTC, hczs commented on libcity/config/data/STPGCNDataset.json
> +  "time_intervals": 720,
已修改

2024-07-02 08:34 UTC, Kazeya27 approved these changes

2024-07-02 08:34 UTC, merged