fix: TESTAM add vocab_size parameter and TimeMixer input adjust to the BTNF
LibCity/Bigscity-LibCity pull request #426
Opened 2024-06-21 10:29 UTC by hczs

本次修改三个问题：
1. TESTAM 模型添加 vocab_size 参数
2. TimeMixer 移除无用的内部配置类
3. TimeMixer 输入由 BTN 改为 BTNF 格式的数组

2024-06-21 16:17 UTC, Kazeya27 requested changes

2024-06-21 16:17 UTC, Kazeya27 commented on libcity/config/model/traffic_state_pred/TESTAM.json
> +  "vocab_size": 288
这个vocab_size也是一样的，它代表一天中有几个时间片，可以从dataset的time_intervals计算得到，就不用显示地在配置文件中定义了。

2024-06-21 16:17 UTC, Kazeya27 commented on libcity/model/traffic_flow_prediction/TimeMixer.py
> +        dec_out = dec_out.view(B, T, int(N / self.feature_dim), self.feature_dim)
这里你可以先对输出做一个unsqueeze(-1)作为feature的维度，然后将self.projection_layer改成二维卷积，或者单独加一个线性层处理feature，不要直接在N这个维度上生成feature

2024-06-24 08:10 UTC, hczs commented on libcity/model/traffic_flow_prediction/TimeMixer.py
> +        dec_out = dec_out.view(B, T, int(N / self.feature_dim), self.feature_dim)
更换了下思路，是在输入之前和最后输出的时候各加了一个线性层处理feature，下面是运行结果指标
==========PEMSD8==========
libcity: MAE: 15.80,  MAPE: 10.18%, RMSE: 24.98
paper: MAE: 15.22,  MAPE: 9.67%, RMSE: 24.26
==========PEMSD4-epoch30==========
libcity: MAE: 19.40,  MAPE: 13.35%, RMSE: 31.14
paper: MAE: 19.21,  MAPE: 12.53%, RMSE: 30.92

2024-06-24 10:06 UTC, hczs commented
最新提交
1. https://github.com/LibCity/Bigscity-LibCity/pull/426/commits/766c164546b1bb718113ab1baae5db1ed7c3ee04
2. https://github.com/LibCity/Bigscity-LibCity/pull/426/commits/7f9f537daf472fdb8b67ed311e481c893ffe56e2

修改了两个问题
1. TESTAM vocab_size 参数改为使用 time_intervals 参数来计算
2. TimeMixer 输入输出的时候都添加一个线性层来处理feature问题

下面是运行结果指标
==========PEMSD8==========
libcity: MAE: 15.80, MAPE: 10.18%, RMSE: 24.98
paper: MAE: 15.22, MAPE: 9.67%, RMSE: 24.26
==========PEMSD4-epoch30==========
libcity: MAE: 19.40, MAPE: 13.35%, RMSE: 31.14
paper: MAE: 19.21, MAPE: 12.53%, RMSE: 30.92

2024-07-02 08:36 UTC, Kazeya27 approved these changes

2024-07-02 08:36 UTC, merged