feat: add Model MegaCRN
LibCity/Bigscity-LibCity pull request #427
Opened 2024-07-01 06:45 UTC by hczs

## 任务执行配置信息

数据集配置文件（TrafficStatePointDataset.json）

```json
{
  "batch_size": 64,
  "cache_dataset": false,
  "num_workers": 0,
  "pad_with_last_sample": true,
  "train_rate": 0.7,
  "eval_rate": 0.1,
  "scaler": "standard",
  "load_external": true,
  "normal_external": false,
  "ext_scaler": "none",
  "input_window": 12,
  "output_window": 12,
  "add_time_in_day": true,
  "add_day_in_week": false
}
```

模型配置文件（MegaCRN.json）

```json
{
  "rnn_units": 64,
  "num_layers": 1,
  "cheb_k": 3,
  "ycov_dim": 1,
  "cl_decay_steps": 2000,
  "use_curriculum_learning": true,
  "mem_num": 20,
  "mem_dim": 64,
  "dim_in": 1
}
```

执行器配置信息（MegaCRNExecutor.json）
```json
{
  "max_epoch": 200,
  "learner": "adam",
  "learning_rate": 0.01,
  "lr_epsilon": 0.001,
  "lr_decay": true,
  "lr_scheduler": "multisteplr",
  "lr_decay_ratio": 0.1,
  "milestones": [50,100],
  "clip_grad_norm": true,
  "max_grad_norm": 5,
  "use_early_stop": true,
  "patience": 20,
  "lamb": 0.01,
  "lamb1": 0.01
}
```

## 任务执行结果

模型评价指标对比如下
- METR_LA
  | METR_LA | MAE/RMSE/MAPE@3rd step | MAE/RMSE/MAPE@6th step | MAE/RMSE/MAPE@12th step |
  | ---- | ---- | ---- | ---- |
  | MegaCRN| 2.52/4.94/6.44% | 2.93/6.06/7.96% | 3.38/7.23/9.72% |
  | LibCity | 2.67/5.07/6.88% | 3.08/6.18/8.36% | 3.55/7.38/10.18% |

- PEMS_BAY
  | PEMS_BAY | MAE/RMSE/MAPE@3rd step | MAE/RMSE/MAPE@6th step | MAE/RMSE/MAPE@12th step |
  | ---- | ---- | ---- | ---- |
  | MegaCRN | 1.28/2.72/2.67% | 1.60/3.68/3.57% | 1.88/4.42/4.41% |
  | LibCity | 1.34/2.85/2.79% | 1.69/3.81/3.80% | 2.01/4.56/4.78% |

2024-07-07 14:39 UTC, Kazeya27 requested changes

2024-07-07 14:39 UTC, Kazeya27 commented on libcity/model/traffic_speed_prediction/MegaCRN.py
> +        self.input_dim = config.get("dim_in", 1)
从data_feature里面去拿这个参数，不要额外在config里面去设定。

2024-07-07 14:39 UTC, Kazeya27 commented on libcity/model/traffic_speed_prediction/MegaCRN.py
> +        self.output_dim = config.get("output_dim", 1)
从data_feature里面去拿这个参数，不要额外在config里面去设定。

2024-07-07 14:39 UTC, Kazeya27 commented on libcity/model/traffic_speed_prediction/MegaCRN.py
> +        return self.forward(x, ycov, y, batches_seen)
没有写calculate_loss方法吗？

2024-07-07 14:39 UTC, Kazeya27 commented on libcity/executor/megacrn_executor.py
> +        def default_train_loss(batch):
为什么不在Model类里面写这个呢

2024-07-07 14:39 UTC, Kazeya27 commented on libcity/executor/megacrn_executor.py
> +    def _valid_epoch(self, eval_dataloader, epoch_idx, loss_func=None):
这个方法比起父类有改动吗？

2024-07-07 14:39 UTC, Kazeya27 commented on libcity/executor/megacrn_executor.py
> +                output, _, _, _, _ = self.model.predict(batch)
把Model类的predict改为返回一个值（比如拆分为两个方法，predict去调用这个方法，然后返回一个值），不要这么写。

2024-07-09 02:45 UTC, hczs commented
最新的提交 https://github.com/LibCity/Bigscity-LibCity/pull/427/commits/0418d71c226b6ab3c9de9787a84537ccbacbe457 已修改以上问题：
1. input_dim 和 output_dim 取值方式
2. calculate_loss 放到模型中实现
3. 简化整理 executor 中的代码，并整理模型和执行器配置文件内容

2024-07-09 07:21 UTC, Kazeya27 approved these changes

2024-07-09 07:21 UTC, merged