astgnn update
LibCity/Bigscity-LibCity pull request #441
Opened 2024-09-24 02:48 UTC by luiluizi

PEMSD4 | libcity | ASTGNN
-- | -- | --
MAE: | 18.85 | 18.60
RMSE: | 31.21 | 30.91
MAPE: | 12.51% | 12.36%

2024-09-26 08:18 UTC, Kazeya27 requested changes

2024-09-26 08:18 UTC, Kazeya27 commented on libcity/model/traffic_flow_prediction/__init__.py
> +# from libcity.model.traffic_flow_prediction.STPGCN import STPGCN
别把人家注释了

2024-09-26 08:18 UTC, Kazeya27 commented on libcity/model/traffic_flow_prediction/ASTGNNCommon.py
> +        return batch['y'].transpose(1, 2).transpose(2, 3)[: ,: ,:self.output_dim ,:].transpose(-1, -2).transpose(-2, -3)  # B N T F
为什么还有一个Common

2024-09-27 03:06 UTC, luiluizi commented on libcity/model/traffic_flow_prediction/ASTGNNCommon.py
> +        return batch['y'].transpose(1, 2).transpose(2, 3)[: ,: ,:self.output_dim ,:].transpose(-1, -2).transpose(-2, -3)  # B N T F
这是学长之前的要求，可以使模型能用一般的TrafficStateGridDataset和TrafficStatePointDataset，而不使用C P T三段数据产生输入数据

2024-11-06 11:04 UTC, Kazeya27 approved these changes

2024-11-06 11:05 UTC, merged